services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - chromadb:/db/chromadb

volumes:
  chromadb:
