site_name: USFS Data Catalog
theme:
  name: material
#   palette:
#     primary: indigo
#     accent: indigo

plugins:
    - search

markdown_extensions:
#   - admonition
#   - codehilite
#   - footnotes
#   - meta
#   - toc:
#       permalink: True
    - attr_list
nav:
  - Home: index.md

extra_css:
  - extras/styles.css
