site_name: USFS Data Catalog
theme:
  name: readthedocs
#   palette:
#     primary: indigo
#     accent: indigo
plugins:
    - search

nav:
  - Home: index.md
  - Introduction: introduction.md

extra_css:
  - extras/styles.css
