[project]
name = "crawlers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arrow>=1.3.0",
    "bs4>=0.0.2",
    "chromadb>=1.0.10",
    "lxml>=5.4.0",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
