services:

  #catalog:
  #  build:
  #    context: ./catalog
  #    dockerfile: Dockerfile
  #  env_file:
  #    - .env
  #  volumes:
  #    - $PWD:/catalog
  #  tty: true
  #  stdin_open: true
  #  restart: unless-stopped

  pgsql:
    extends:
      file: ./pgsql/compose.yml
      service: postgres
    env_file:
      - .env

  mongodb:
    extends:
      file: ./mongodb/compose.yml
      service: mongodb
    env_file:
      - .env

  adminer:
    extends:
      file: ./pgsql/compose.yml
      service: adminer
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    hostname: openwebui
    ports:
      - "3000:8080" # Maps host port 3000 to container port 8080
    volumes:
      - openwebui_data:/app/backend/data
    env_file:
      - .env
    # environment:
    #   - OLLAMA_BASE_URL=http://ollama:11434 # Connects Open WebUI to the Ollama service
    #   - WEBUI_SECRET_KEY=your_secret_key_here # **IMPORTANT**: Change this to a strong, unique key
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  pgdata:
  mongodata:
  ollama_data:
  openwebui_data:

