model_list:
    - model_name: ollama/llama3.1 # The name you use in litellm.completion
      litellm_params:
        model: ollama/llama3.1 # The actual model identifier for the provider
        api_base: "http://ollama:11434" # Default, change if needed

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/LITELLM_DATABASE_URL

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  set_verbose: true
  json_logs: true
